# Generated by Django 5.2.8 on 2025-12-03 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='credentials_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
