# Generated by Django 5.2.8 on 2025-12-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0002_empty'),
        ('field_app', '0003_assessor_credentials_sent_assessor_email_and_more'),
    ]

    operations = [
    ]
